/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    CalculationTypeList: typeof import('./src/components/CalculationTypeList.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    MainDisplay: typeof import('./src/components/MainDisplay.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
